### ISSUE TITLE
Updating of your data

### ISSUE THREAD

**Issue by JiPiBi** [bzg/covid19-fr#5]
Hi 
It seems that your site is not updated 
On my side I make a record of the data from sante publique france by a copy paste in an excel sheet 
Perhaps you also know this site on French data : 
https://github.com/opencovid19-fr/data

**Comment by bzg** [comment]
Thanks for letting me know, fixed now.  Yes, I know https://github.com/opencovid19-fr/data and it is much richer than the SPF html/pdf bulletins.

You might also want to check this dataset: https://www.data.gouv.fr/fr/datasets/donnees-relatives-a-lepidemie-du-covid-19/
